image:
  repository: artifactory.dagility.com/docker/vdcheckzxcv-backend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: vdcheckzxcv-backend-habitat-testttttttttttttttttttttttttttttttttttttttttttttttttttt.dagility.com
    paths:
    - /
serviceAccount:
  create: false
